version = 1

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "16"

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["5000"]

[[transformers]]
name = "rubocop"
enabled = true

[[transformers]]
name = "google-java-format"
enabled = true